# Generated by Django 2.2 on 2019-07-03 03:39

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='benchmark',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('benchmark_name', models.CharField(max_length=256)),
                ('end_date', models.DateTimeField()),
                ('benchmark_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('c_name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_roll_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('s_first_name', models.CharField(max_length=256)),
                ('s_last_name', models.CharField(max_length=256)),
                ('s_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('s_department', models.CharField(choices=[('CS', 'Computer Science'), ('EE', 'Electrical Enginering'), ('CHE', 'Chemical Enginering'), ('BBA', 'Management Department')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Class')),
                ('s_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login_app.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('position1', smart_selects.db_fields.GroupedForeignKey(group_field='s_subject', on_delete=django.db.models.deletion.CASCADE, related_name='m1', to='dashboard_app.Student_Enroll')),
                ('position2', smart_selects.db_fields.GroupedForeignKey(group_field='s_subject', on_delete=django.db.models.deletion.CASCADE, related_name='m2', to='dashboard_app.Student_Enroll')),
                ('position3', smart_selects.db_fields.GroupedForeignKey(group_field='s_subject', on_delete=django.db.models.deletion.CASCADE, related_name='m3', to='dashboard_app.Student_Enroll')),
                ('team_subj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Subject')),
            ],
            options={
                'unique_together': {('position1', 'position2', 'position3')},
            },
        ),
        migrations.CreateModel(
            name='uploaded_csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='total_performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField(max_length=4)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('Student_perf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Student_Enroll')),
            ],
        ),
        migrations.CreateModel(
            name='total_perf_hist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('total_val', models.FloatField(max_length=4)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('stud_pref_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Student_Enroll')),
            ],
        ),
        migrations.CreateModel(
            name='team_performance_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('total_perf', models.FloatField(max_length=4)),
                ('team_p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='team_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('team_id', models.IntegerField()),
                ('member_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_1', to='dashboard_app.Student_Enroll')),
                ('member_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_2', to='dashboard_app.Student_Enroll')),
                ('member_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_3', to='dashboard_app.Student_Enroll')),
            ],
        ),
        migrations.AddField(
            model_name='student_enroll',
            name='s_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Subject'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('quiz_number', models.IntegerField()),
                ('quiz_title', models.CharField(max_length=256)),
                ('quiz_total_marks', models.FloatField(max_length=4)),
                ('quiz_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Subject')),
                ('quiz_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login_app.Teacher')),
            ],
            options={
                'unique_together': {('quiz_subject', 'quiz_title')},
            },
        ),
        migrations.CreateModel(
            name='pref_class_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('A_count', models.IntegerField()),
                ('B_count', models.IntegerField()),
                ('G_count', models.IntegerField()),
                ('subj_of_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='predictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('prediction_class', models.CharField(choices=[('G', 'Good'), ('A', 'Avarage'), ('B', 'Bad')], max_length=5)),
                ('Student_Prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Student_Enroll')),
            ],
        ),
        migrations.CreateModel(
            name='intervention',
            fields=[
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('intervention_id', models.AutoField(primary_key=True, serialize=False)),
                ('inter_postion', models.IntegerField()),
                ('inter_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Student_Enroll')),
                ('inter_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('student_position', models.IntegerField()),
                ('student_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Student_Enroll')),
                ('student_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('fnl_total_marks', models.FloatField(max_length=4)),
                ('fnl_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Subject')),
                ('fnl_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login_app.Teacher')),
            ],
            options={
                'unique_together': {('fnl_subject',)},
            },
        ),
        migrations.CreateModel(
            name='Enroll_Sessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('ses_number', models.IntegerField()),
                ('ses_title', models.CharField(max_length=256)),
                ('ses_total_marks', models.FloatField(max_length=4)),
                ('ses_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Subject')),
                ('ses_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login_app.Teacher')),
            ],
            options={
                'unique_together': {('ses_subject', 'ses_title')},
            },
        ),
        migrations.CreateModel(
            name='avg_performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('avg_perf', models.FloatField(max_length=4)),
                ('Subject_pref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('ass_number', models.IntegerField()),
                ('ass_title', models.CharField(max_length=256)),
                ('ass_total_marks', models.FloatField(max_length=4)),
                ('ass_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Subject')),
                ('ass_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login_app.Teacher')),
            ],
            options={
                'unique_together': {('ass_subject', 'ass_title')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='student_enroll',
            unique_together={('s_subject', 's_student')},
        ),
        migrations.CreateModel(
            name='SessionalMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('sesm_obtained_marks', models.FloatField(max_length=4)),
                ('sesm_sessional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Enroll_Sessional')),
                ('sesm_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Student_Enroll')),
            ],
            options={
                'unique_together': {('sesm_student', 'sesm_sessional')},
            },
        ),
        migrations.CreateModel(
            name='QuizMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('quizm_obtained_marks', models.FloatField(max_length=4)),
                ('quizm_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Quiz')),
                ('quizm_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Student_Enroll')),
            ],
            options={
                'unique_together': {('quizm_student', 'quizm_quiz')},
            },
        ),
        migrations.CreateModel(
            name='FinalMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('fnlm_obtained_marks', models.FloatField(max_length=4)),
                ('fnlm_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Final')),
                ('fnlm_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Student_Enroll')),
            ],
            options={
                'unique_together': {('fnlm_student', 'fnlm_final')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('assm_obtained_marks', models.FloatField(max_length=4)),
                ('assm_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Assignment')),
                ('assm_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Student_Enroll')),
            ],
            options={
                'unique_together': {('assm_student', 'assm_assignment')},
            },
        ),
    ]
