# Generated by Django 2.2 on 2019-07-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_perf_hist',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='total_performance',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
