# Generated by Django 2.2 on 2019-07-03 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_auto_20190702_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('fnl_total_marks', models.FloatField(max_length=4)),
                ('fnl_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='FinalMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('fnlm_obtained_marks', models.FloatField(max_length=4)),
                ('fnlm_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Final')),
                ('fnlm_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Student_Enroll')),
            ],
        ),
    ]
