# Generated by Django 2.2 on 2019-07-03 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0001_initial'),
        ('dashboard_app', '0003_final_finalmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='fnl_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Login_app.Teacher'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='final',
            unique_together={('fnl_subject',)},
        ),
        migrations.AlterUniqueTogether(
            name='finalmarks',
            unique_together={('fnlm_student', 'fnlm_final')},
        ),
    ]
