# Generated by Django 2.2 on 2019-07-10 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_auto_20190703_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ass_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enroll_sessional',
            name='ses_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='final',
            name='fnl_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.Class'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='student_enroll',
            unique_together={('s_subject', 's_student', 's_class')},
        ),
    ]
