# Generated by Django 2.2 on 2019-07-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_auto_20190710_2047'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('position3', 'position1', 'position2'), ('position3', 'position2', 'position1'), ('position1', 'position3', 'position2'), ('position2', 'position3', 'position1'), ('position2', 'position1', 'position3'), ('position1', 'position2', 'position3')},
        ),
    ]
