# Generated by Django 2.2 on 2019-07-03 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('t_departmant', models.CharField(choices=[('CS', 'Computer Science'), ('EE', 'Electrical Enginering'), ('CHE', 'Chemical Enginering'), ('BBA', 'Management Department')], max_length=3)),
                ('t_teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
